replicaCount: 1

image:
  repository: docker.io/interestingstorage/waffler  
  pullPolicy: IfNotPresent
  tag: "0.2.0"

imagePullSecrets:
  name: interestingstorage

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080


resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
